describe('Mind format registration', () => {
    it('Mindformat successful registration', () => {
      cy.log('Переход на сайт mindformat')
      cy.visit('https://mindformat.ru')
      cy.log('Регистрация нового пользователя')
      cy.contains('Регистрация').click()
      cy.wait(5000)
      cy.log('Ввод имени пользователя')
      cy.get('#name').type('1fsadfasdf22', )
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
      cy.get('#name').clear()
      cy.wait(5000)
      cy.get('#name').type('asdf^2#$!')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
      cy.get('#name').clear()
      cy.wait(5000)
      cy.get('#name').type('asdfdsafv      sadf sadf')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
      cy.get('#name').clear()
      cy.wait(5000)
      cy.get('#name').type('345345435^^&^%&@@@22')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
      cy.get('#name').clear()
      cy.wait(5000)
      cy.get('#name').type('45453453   345    345 ')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
      cy.get('#name').clear()
      cy.wait(5000)
      cy.get('#name').type('%^$%^$%^ $ $$$')
      cy.wait(5000)
      cy.log('Ввод пароля')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('1fsadfasdf22', )
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('asdf^2#$!')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('asdfdsafv      sadf sadf')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('345345435^^&^%&@@@')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('45453453   345    345 ')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('%^$%^$%^ $$$$$$$ ^&^')
      cy.wait(5000)
      cy.log('Ввод электронной почты')
      cy.get('#email').type('1fsadfasdf22@3f3ffsdf.com', )
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
      cy.get('#email').clear()
      cy.wait(5000)
      cy.get('#email').type('asdf^#$!@asdf43f4.net')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
      cy.get('#email').clear()
      cy.wait(5000)
      cy.get('#email').type('453543r5&&&*****##±±@u4t.cce')
      cy.wait(5000)
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
      cy.wait(5000)
      cy.log('Принятия политик соглашения')
      cy.get('#policy-agree').click()
      cy.get('#terms-agree').click()
      cy.get('#offers-agree').click()
      cy.wait(5000)
      cy.log('Регистрация нового пользователя')
      cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.d-flex.justify-content-between.align-items-center.mt-3 > button > div > div').click()
      cy.get('#__layout > div > div:nth-child(1) > div > div.header.py-3 > div > div.d-none.d-sm-flex.justify-content > ul > li:nth-child(5) > a').should('have.attr', 'href', '/profile')
    })
    it('Mindformat attempt of registration without agreement', () => {
        cy.log('Переход на сайт mindformat')
        cy.visit('https://mindformat.ru')
        cy.log('Регистрация нового пользователя')
        cy.contains('Регистрация').click()
        cy.wait(5000)
        cy.log('Ввод имени пользователя')
        cy.get('#name').type('1fsadfasdf22', )
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.get('#name').type('asdf^2#$!')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.get('#name').type('asdfdsafv      sadf sadf')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.get('#name').type('345345435^^&^%&@@@22')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.get('#name').type('45453453   345    345 ')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('not.contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.get('#name').type('%^$%^$%^ $$$$$$$ ^&^')
        cy.wait(5000)
        cy.log('Ввод пароля')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('1fsadfasdf22', )
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('asdf^2#$!')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('asdfdsafv      sadf sadf')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('345345435^^&^%&@@@')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('45453453   345    345 ')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('not.contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('%^$%^$%^ $$$$$$$ ^&^')
        cy.wait(5000)
        cy.log('Ввод электронной почты')
        cy.get('#email').type('1fsadfasdf22@3f3ffsdf.com', )
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('asdf^#$!@asdf43f4.net')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('453543535&&&*****##±±@utj4t4t.covve')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('not.contain.text', 'Поле e-mail обязательно для заполнения')
        cy.wait(5000)
        cy.log('Попытка регистрации нового пользователя')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.d-flex.justify-content-between.align-items-center.mt-3 > button > div > div').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.form-check.mb-2.mt-4 > span > div').should('contain.text', 'Поле policy обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(5) > span > div').should('contain.text', 'Поле terms обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(6) > span > div').should('contain.text', 'Поле offer обязательно для заполнения')
        cy.get('#policy-agree').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.d-flex.justify-content-between.align-items-center.mt-3 > button > div > div').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(5) > span > div').should('contain.text', 'Поле terms обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(6) > span > div').should('contain.text', 'Поле offer обязательно для заполнения')
        cy.get('#terms-agree').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.d-flex.justify-content-between.align-items-center.mt-3 > button > div > div').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(6) > span > div').should('contain.text', 'Поле offer обязательно для заполнения')
        cy.get('#policy-agree').click()
        cy.get('#offers-agree').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.form-check.mb-2.mt-4 > span > div').should('contain.text', 'Поле policy обязательно для заполнения')
        cy.get('#terms-agree').click()
        cy.get('#policy-agree').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(5) > span > div').should('contain.text', 'Поле terms обязательно для заполнения')
        cy.get('#offers-agree').click()
        cy.get('#policy-agree').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.form-check.mb-2.mt-4 > span > div').should('contain.text', 'Поле policy обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(5) > span > div').should('contain.text', 'Поле terms обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(6) > span > div').should('contain.text', 'Поле offer обязательно для заполнения')
      })
    it('Mindformat attempt of registration with agreement', () => {
        cy.log('Переход на сайт mindformat')
        cy.visit('https://mindformat.ru')
        cy.log('Регистрация нового пользователя')
        cy.contains('Регистрация').click()
        cy.wait(5000)
        cy.log('Ввод имени пользователя')
        cy.get('#name').type('    ', )
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#name').clear()
        cy.wait(5000)
        cy.log('Ввод пароля')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').type('      ',)
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > input').clear()
        cy.wait(5000)
        cy.log('Ввод электронной почты')
        cy.get('#email').type('    ')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail обязательно для заполнения')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('    @2ertertert.ri')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('    @fsdf#@#@#@.рр555')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('    @244444%%^^^.рф')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('    @2ertertert.')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
        cy.get('#email').clear()
        cy.wait(5000)
        cy.get('#email').type('    ')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail обязательно для заполнения')
        cy.wait(5000)
        cy.get('#email').type('    @')
        cy.wait(5000)
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
        cy.wait(5000)
        cy.log('Принятия политик соглашения')
        cy.get('#policy-agree').click()
        cy.get('#terms-agree').click()
        cy.get('#offers-agree').click()
        cy.wait(5000)
        cy.log('Попытка регистрации нового пользователя')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div.d-flex.justify-content-between.align-items-center.mt-3 > button > div > div').click()
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div:nth-child(1) > span > div').should('contain.text', 'Поле Имя обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(1) > div.mb-3 > span > div').should('contain.text', 'Поле Пароль обязательно для заполнения')
        cy.get('#__layout > div > div.flex-fill > div > div > div > div > div > span > form > div:nth-child(2) > span > div').should('contain.text', 'Поле e-mail должно быть действительным электронным адресом')
      })
})